-- DEPRECATED: do not use the old permissive CMS policies.
-- Use `production_schema.sql`, which implements role-based RLS, audit logging,
-- events, announcements, prayer-time administration, team profiles and livestream settings.
