import React,{useState,useEffect}from'react';
import{Link}from'react-router-dom';
import{Search,ExternalLink,Save,Upload,Smartphone,Monitor,ArrowUpRight,Lock,Image as ImageIcon}from'lucide-react';
import{supabase}from'@/lib/supabaseClient';
import{useContent}from'@/context/ContentContext';
import{EDITABLE_PAGES,pageDefaults,pageKey,overviewPaths}from'@/content/editablePages';
import PageSectionsEditor from '@/components/admin/PageSectionsEditor';
import CommunityLinksEditor from '@/components/admin/CommunityLinksEditor';

export default function PageEditor(){
 const[selected,setSelected]=useState('/'),[query,setQuery]=useState(''),[draft,setDraft]=useState({}),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false),[mobile,setMobile]=useState(true),[revision,setRevision]=useState(0);
 const{refreshContent}=useContent();const page=EDITABLE_PAGES.find(p=>p.path===selected);
 useEffect(()=>{let active=true;setLoading(true);setError('');setMessage('');supabase.from('page_content').select('content_value').eq('content_key',pageKey(selected)).maybeSingle().then(({data,error})=>{if(!active)return;if(error)throw error;setDraft({...pageDefaults(page),...(data?.content_value?JSON.parse(data.content_value):{})});setDirty(false);}).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false};},[selected]);
 useEffect(()=>{const guard=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);
 const change=(key,value)=>{setDraft(d=>({...d,[key]:value}));setDirty(true);setMessage('');};
 const choose=path=>{if(busy)return;if(dirty&&!window.confirm('Discard unsaved changes and open another page?'))return;setSelected(path);};
 const persist=async next=>{const payload={title:next.title||'',body:next.body||'',image:next.image||''};const{data,error}=await supabase.from('page_content').upsert({content_key:pageKey(selected),content_value:JSON.stringify(payload),content_type:'json',page:selected},{onConflict:'content_key'}).select('content_key');if(error)throw error;if(data?.length!==1)throw new Error('The page was not saved.');await refreshContent();setDraft(next);setDirty(false);setRevision(n=>n+1);};
 const upload=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);setError('');setMessage('');try{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024)throw new Error('Choose a JPG, PNG or WebP under 8 MB.');const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type];const path=`pages/${crypto.randomUUID()}.${ext}`;const{error}=await supabase.storage.from('site-images').upload(path,file,{upsert:false});if(error)throw error;const url=supabase.storage.from('site-images').getPublicUrl(path).data.publicUrl;const next={...draft,image:url};await persist(next);setMessage('Picture uploaded and published.');}catch(e){setError(e.message)}finally{setBusy(false)}};
 const save=async()=>{setBusy(true);setError('');setMessage('');try{if(draft.image&&!/^https:\/\//i.test(draft.image))throw new Error('Use an HTTPS image URL or upload a picture.');await persist(draft);setMessage('Published. Your website now shows these changes.');}catch(e){setError(e.message)}finally{setBusy(false)}};
 const visible=EDITABLE_PAGES.filter(p=>`${p.name} ${p.group}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="admin-workspace"><div className="admin-heading"><div><span className="admin-eyebrow">YOUR WEBSITE</span><h2>Pages & pictures</h2><p>Choose a page. Edit text, pictures, backgrounds and sections. Changes are saved in Supabase.</p></div><Link className="admin-button" to="/admin/home-tiles">Edit home tiles <ArrowUpRight size={16}/></Link></div>
 <CommunityLinksEditor/>
 <div className="admin-page-layout"><aside className="admin-panel admin-page-picker"><label className="admin-search"><Search size={16}/><input aria-label="Find a page" placeholder="Find a page…" value={query} onChange={e=>setQuery(e.target.value)}/></label><nav>{[...new Set(visible.map(p=>p.group))].map(group=><div key={group}><h4>{group}</h4>{visible.filter(p=>p.group===group).map(p=><button disabled={busy} key={p.path} onClick={()=>choose(p.path)} className={selected===p.path?'selected':''}>{p.name}<span>›</span></button>)}</div>)}</nav><small><Lock size={12}/> Pages and menu links are fixed.</small></aside>
 <div className="admin-page-main"><section className="admin-panel"><div className="admin-heading"><div><h3>{page.name}</h3><p>{selected}</p></div><a href={selected} target="_blank" rel="noreferrer" className="admin-button">Open page <ExternalLink size={15}/></a></div>
 {overviewPaths.has(selected)&&<p className="admin-hint">Edit the main information panel here, then use Page sections & backgrounds below for extra blocks and images.</p>}
 {error&&<div role="alert" className="admin-error">{error}</div>}{message&&<div role="status" className="admin-success">{message}</div>}
 <fieldset disabled={busy||loading}><label>Heading<textarea rows="2" value={draft.title||''} onChange={e=>change('title',e.target.value)}/></label><label>Information<textarea rows="6" placeholder="Add the information visitors need…" value={draft.body||''} onChange={e=>change('body',e.target.value)}/></label><label>Picture URL<input type="url" value={draft.image||''} placeholder="https://… or upload below" onChange={e=>change('image',e.target.value)}/></label><div className="admin-actions"><label className="admin-button"><Upload size={16}/>Upload & publish picture<input type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={upload}/></label>{draft.image&&<button type="button" className="admin-button" onClick={()=>change('image','')}>Remove picture</button>}</div></fieldset>
 <div className="admin-actions"><button disabled={busy||loading||!dirty} className="admin-button primary" onClick={save}><Save size={16}/>{busy?'Saving…':'Publish changes'}</button><small>{dirty?'Unsaved changes':'Saved content'}</small></div>
 </section><section className="admin-panel"><span className="admin-eyebrow">CONTENT PREVIEW · {dirty?'UNSAVED':'SAVED'}</span><article className="admin-draft-card">{draft.image?<img src={draft.image} alt="Page picture preview"/>:<div className="admin-picture-empty"><ImageIcon/><span>Add a picture to this page</span></div>}<h2>{draft.title}</h2><p>{draft.body||'Your information will appear here.'}</p></article></section>
 <PageSectionsEditor pagePath={selected}/>
 <section className="admin-panel"><div className="admin-heading"><div><h3>Actual website</h3><p>Published view only. Admin controls are hidden inside this preview.</p></div><div className="admin-actions"><button aria-label="Mobile preview" className={`admin-button ${mobile?'active':''}`} onClick={()=>setMobile(true)}><Smartphone size={17}/></button><button aria-label="Desktop preview" className={`admin-button ${!mobile?'active':''}`} onClick={()=>setMobile(false)}><Monitor size={17}/></button></div></div><div className={`admin-site-preview ${mobile?'mobile':''}`}><iframe key={`${selected}-${revision}`} src={`${selected}${selected.includes('?')?'&':'?'}preview=1`} title={`${page.name} published website preview`}/></div></section></div></div></div>;
}
