import React,{useState,useEffect} from 'react';
import {Upload,Download,Save,Clock3,CheckCircle2} from 'lucide-react';
import {supabase} from '@/lib/supabaseClient';
import {prayerFields,jummahFields,defaultJummah,londonDate,parseTimetable,displayTime} from '@/lib/timetable';

const CSV_TEMPLATE='d_date,fajr_begins,fajr_jamah,sunrise,zuhr_begins,zuhr_jamah,asr_begins,asr_jamah,maghrib_begins,maghrib_jamah,isha_begins,isha_jamah,is_ramadan\r\n';

export default function PrayerEditor(){
 const [date,setDate]=useState(londonDate),[form,setForm]=useState({}),[jummah,setJummah]=useState(defaultJummah),[pending,setPending]=useState(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[error,setError]=useState(''),[version,setVersion]=useState(0),[dates,setDates]=useState([]);
 useEffect(()=>{let active=true;setLoading(true);setError('');Promise.all([
  supabase.from('prayer_times').select('*').eq('d_date',date).maybeSingle(),
  supabase.from('page_content').select('content_value').eq('content_key','jummah_settings').maybeSingle(),
  supabase.from('prayer_times').select('d_date').order('d_date').limit(1000)
 ]).then(([d,j,list])=>{if(!active)return;const failure=d.error||j.error||list.error;if(failure){setError(failure.message);return;}setForm(d.data||{});setDates(list.data||[]);setJummah(j.data?{...defaultJummah,...JSON.parse(j.data.content_value)}:defaultJummah);}).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false};},[date,version]);
 const run=async(fn)=>{setBusy(true);setError('');setMessage('');try{await fn();window.dispatchEvent(new Event('jic-content-updated'));setVersion(v=>v+1);}catch(e){setError(e.message);}finally{setBusy(false);}};
 const saveDay=()=>run(async()=>{const payload={d_date:date,is_ramadan:!!form.is_ramadan};for(const[k]of [...prayerFields,...jummahFields])payload[k]=form[k]||null;
 const{data,error}=await supabase.from('prayer_times').upsert(payload,{onConflict:'d_date'}).select('d_date');if(error)throw error;if(data?.length!==1)throw new Error('The date was not saved.');setMessage(`Saved ${date} to your timetable.`);});
 const importCsv=async(e)=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setError('');setMessage('');setPending(null);try{if(file.size>2*1024*1024)throw new Error('CSV must be under 2 MB.');setPending({name:file.name,rows:parseTimetable(await file.text())});}catch(x){setError(x.message);}};
 const downloadTemplate=()=>{const blob=new Blob(['\uFEFF',CSV_TEMPLATE],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='jic-timetable-template.csv';document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const publish=()=>run(async()=>{const rows=pending.rows;const{data,error}=await supabase.from('prayer_times').upsert(rows,{onConflict:'d_date',defaultToNull:false}).select('d_date');if(error)throw error;if(data?.length!==rows.length)throw new Error('Could not verify every imported date.');setMessage(`${data.length} dates saved to Supabase. The website now uses this timetable.`);setDate(rows[0].d_date);setPending(null);});
 const saveJummah=()=>run(async()=>{const{error}=await supabase.from('page_content').upsert({content_key:'jummah_settings',content_value:JSON.stringify(jummah),content_type:'json',page:'prayer-times'},{onConflict:'content_key'});if(error)throw error;setMessage('Weekly Jummah times published across the website.');});
 return <div className="admin-workspace"><div className="admin-heading"><div><span className="admin-eyebrow">WORSHIP & COMMUNITY</span><h2>Prayer timetable</h2><p>Upload once. Your website reads the saved times.</p></div><a href="/prayer-times" target="_blank" rel="noreferrer" className="admin-button">View timetable ↗</a></div>
 {error&&<div role="alert" className="admin-error">{error}</div>}{message&&<div role="status" className="admin-success"><CheckCircle2 size={18}/>{message}</div>}
 <section className="admin-panel"><div className="admin-section-title"><Upload/><div><h3>Upload your CSV</h3><p>{dates.length?`${dates.length} dates stored · ${dates[0].d_date} to ${dates.at(-1).d_date}`:'No timetable uploaded yet.'}</p></div></div><div className="admin-upload"><strong>Choose your mosque-approved timetable</strong><p>Check the preview, then save. Matching dates are updated; other dates stay as they are.</p><div className="admin-actions"><label className="admin-button primary"><Upload size={17}/>Choose CSV<input disabled={busy||loading} type="file" accept=".csv,text/csv" onChange={importCsv} hidden/></label><button type="button" onClick={downloadTemplate} className="admin-button"><Download size={17}/>CSV template</button></div><small>Downloads as jic-timetable-template.csv · 24-hour times · YYYY-MM-DD or DD/MM/YYYY dates · up to 366 days</small></div>
 {pending&&<div className="admin-import-preview"><h3>{pending.name} · {pending.rows.length} dates</h3><p>{pending.rows.filter(r=>dates.some(d=>d.d_date===r.d_date)).length} existing dates will be updated.</p><div className="admin-table-scroll"><table><thead><tr><th>Date</th><th>Fajr</th><th>Dhuhr</th><th>Asr</th><th>Maghrib</th><th>Isha</th></tr></thead><tbody>{pending.rows.slice(0,5).map(r=><tr key={r.d_date}><td>{r.d_date}</td>{['fajr','zuhr','asr','maghrib','isha'].map(k=><td key={k}>{r[k+'_jamah']}</td>)}</tr>)}</tbody></table></div><small>Preview shows Jama’ah times for the first five dates. All supplied times will be saved.</small><div className="admin-actions"><button disabled={busy} onClick={publish} className="admin-button primary">{busy?'Saving…':`Save ${pending.rows.length} dates`}</button><button disabled={busy} className="admin-button" onClick={()=>setPending(null)}>Cancel</button></div></div>}
 </section><section className="admin-panel"><div className="admin-section-title"><Clock3/><div><h3>Weekly Jummah</h3><p>Default Friday times shown in the header, homepage and Jummah page.</p></div></div><div className="admin-field-grid">{jummahFields.map(([k,title])=><label key={k}>{title}<input disabled={loading||busy} type="time" value={jummah[k]||''} onChange={e=>setJummah({...jummah,[k]:e.target.value})}/></label>)}</div><p className="admin-time-preview">1st Jama’ah {displayTime(jummah.jummah_1_jamah)} · 2nd Jama’ah {displayTime(jummah.jummah_2_jamah)}</p><button disabled={busy||loading||jummahFields.some(([k])=>!jummah[k])} onClick={saveJummah} className="admin-button primary"><Save size={16}/>Save Jummah times</button></section>
 <section className="admin-panel"><h3>Edit a single date</h3><label className="admin-date">Date<input disabled={busy} type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><div className="admin-field-grid">{prayerFields.map(([k,title])=><label key={k}>{title}<input disabled={loading||busy} type="time" value={form[k]?.slice(0,5)||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><label className="admin-check"><input type="checkbox" checked={!!form.is_ramadan} onChange={e=>setForm({...form,is_ramadan:e.target.checked})}/> Ramadan day</label><details><summary>Jummah overrides for this date (optional)</summary><p>Leave blank to use the weekly times above. Friday overrides also appear during the week leading up to that Friday.</p><div className="admin-field-grid">{jummahFields.map(([k,title])=><label key={k}>{title}<input disabled={loading||busy} type="time" value={form[k]?.slice(0,5)||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div></details><button disabled={busy||loading||!date} onClick={saveDay} className="admin-button primary"><Save size={16}/>Save this date</button></section></div>;
}
