import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import {
  CalendarDays, Clock3, Radio, Megaphone, FileText, Users, ShieldCheck,
  LogOut, Home, RefreshCw, Plus, Trash2, Save, Upload, Activity, UserPlus, X,
} from 'lucide-react';
import PrayerEditor from '@/components/admin/PrayerEditor';
import PageEditor from '@/components/admin/PageEditor';
import '@/styles/admin-workspace.css';
import { supabase } from '@/lib/supabaseClient';
import { useAuth } from '@/context/AuthContext';

const input = 'w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:ring-2 focus:ring-amber-500';
const label = 'mb-1 block text-xs font-semibold uppercase tracking-wide text-slate-500';
const btn = 'inline-flex items-center justify-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold transition disabled:opacity-50';
const primary = `${btn} bg-amber-400 text-slate-950 hover:bg-amber-300`;
const ghost = `${btn} border border-slate-300 bg-white text-slate-700 hover:bg-slate-50`;
const danger = `${btn} bg-red-50 text-red-700 hover:bg-red-100`;

const SECTIONS = [
  ['dashboard', 'Overview', Activity, 'dashboard'],
  ['prayer', 'Timetable & Jummah', Clock3, 'prayer_times'],
  ['events', 'Events', CalendarDays, 'events'],
  ['announcements', 'Announcements', Megaphone, 'announcements'],
  ['livestream', 'Livestream', Radio, 'livestream'],
  ['content', 'Website & pages', FileText, 'content'],
  ['team', 'Meet the team', Users, 'team'],
  ['users', 'Users & roles', ShieldCheck, 'users'],
  ['audit', 'Audit log', Activity, 'audit'],
];

function Field({ title, children, className = '' }) {
  return <label className={className}><span className={label}>{title}</span>{children}</label>;
}

function Notice({ message, error }) {
  if (!message) return null;
  return <div className={`mb-4 rounded-lg px-4 py-3 text-sm ${error ? 'bg-red-50 text-red-700' : 'bg-emerald-50 text-emerald-700'}`}>{message}</div>;
}

function Empty({ children }) { return <div className="rounded-xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">{children}</div>; }

function formatDateTime(value) {
  if (!value) return '';
  const d = new Date(value);
  return Number.isNaN(d.getTime()) ? value : d.toLocaleString('en-GB');
}

async function uploadImage(file, folder = 'admin') {
  if (!file) return null;
  if (!file.type.startsWith('image/')) throw new Error('Please choose an image file.');
  if (file.size > 8 * 1024 * 1024) throw new Error('Image must be under 8 MB.');
  const ext = file.name.split('.').pop()?.toLowerCase() || 'jpg';
  const safe = `${crypto.randomUUID()}.${ext}`;
  const path = `${folder}/${safe}`;
  const { error } = await supabase.storage.from('site-images').upload(path, file, { cacheControl: '3600', upsert: false });
  if (error) throw error;
  return supabase.storage.from('site-images').getPublicUrl(path).data.publicUrl;
}

function DashboardSection({onChoose}) {
  const [stats, setStats] = useState(null);
  const load = useCallback(async () => {
    const today = new Date().toISOString().slice(0, 10);
    const [events, announcements, prayers, team] = await Promise.all([
      supabase.from('events').select('*', { count: 'exact', head: true }).gte('event_date', today),
      supabase.from('announcements').select('*', { count: 'exact', head: true }).eq('published', true),
      supabase.from('prayer_times').select('*', { count: 'exact', head: true }).gte('d_date', today),
      supabase.from('team_members').select('*', { count: 'exact', head: true }).eq('published', true),
    ]);
    setStats({ events: events.count ?? 0, announcements: announcements.count ?? 0, prayers: prayers.count ?? 0, team: team.count ?? 0 });
  }, []);
  useEffect(() => { load(); }, [load]);
  const cards = [
    ['Upcoming events', stats?.events, CalendarDays], ['Live announcements', stats?.announcements, Megaphone],
    ['Timetable days loaded', stats?.prayers, Clock3], ['Published team members', stats?.team, Users],
  ];
  return <div>
    <div className="mb-6 flex items-center justify-between"><div><span className="admin-eyebrow">JAMATIA ISLAMIC CENTRE</span><h2 className="text-2xl font-bold">Your website, at a glance</h2><p className="text-sm text-slate-500">Update the information your community sees.</p></div><button onClick={load} className={ghost}><RefreshCw size={15}/>Refresh</button></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([name, value, Icon]) => <div key={name} className="rounded-2xl border bg-white p-5 shadow-sm"><Icon className="mb-4 text-amber-600"/><div className="text-3xl font-bold">{value ?? '—'}</div><div className="text-sm text-slate-500">{name}</div></div>)}</div>
    <div className="admin-shortcuts">
      <button onClick={()=>onChoose('content')}><FileText/><strong>Pages & pictures</strong><span>Find a page and edit its information</span><b>Open editor →</b></button>
      <Link to="/admin/home-tiles"><Home/><strong>Homepage tiles</strong><span>Change the four tile pictures and text</span><b>Edit tiles →</b></Link>
      <button onClick={()=>onChoose('prayer')}><Clock3/><strong>Timetable & Jummah</strong><span>Upload a CSV or update prayer times</span><b>Manage times →</b></button>
    </div><section className="admin-panel"><div className="admin-heading"><div><span className="admin-eyebrow">LIVE PREVIEW</span><h3>What visitors see</h3><p>Browse the actual website below.</p></div><Link to="/" className="admin-button">Open website ↗</Link></div><div className="admin-site-preview"><iframe src="/" title="JIC live website preview"/></div></section>
  </div>;
}

function EventsSection() {
  const blank = { title:'', description:'', event_date:'', start_time:'', end_time:'', location:'Jamatia Islamic Centre', speaker:'', poster_url:'', registration_url:'', livestream_url:'', category:'community', featured:false, published:false };
  const [rows, setRows] = useState([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState(null); const [msg,setMsg]=useState(''); const [err,setErr]=useState(false); const [busy,setBusy]=useState(false);
  const load = useCallback(async()=>{ const {data,error}=await supabase.from('events').select('*').order('event_date',{ascending:false}); if(error){setErr(true);setMsg(error.message)} else setRows(data||[]);},[]);
  useEffect(()=>{load()},[load]);
  const save=async(e)=>{e.preventDefault();setBusy(true);setMsg('');try{const payload={...form,start_time:form.start_time||null,end_time:form.end_time||null};const q=editing?supabase.from('events').update(payload).eq('id',editing):supabase.from('events').insert(payload);const {error}=await q;if(error)throw error;setForm(blank);setEditing(null);setMsg('Event saved.');setErr(false);await load();}catch(x){setErr(true);setMsg(x.message)}finally{setBusy(false)}};
  const edit=r=>{setEditing(r.id);setForm({ ...blank, ...r, start_time:r.start_time?.slice(0,5)||'', end_time:r.end_time?.slice(0,5)||'' });window.scrollTo({top:0,behavior:'smooth'})};
  const del=async id=>{if(!confirm('Delete this event?'))return;const {error}=await supabase.from('events').delete().eq('id',id);if(error){setErr(true);setMsg(error.message)}else load()};
  const poster=async e=>{try{setBusy(true);const url=await uploadImage(e.target.files?.[0],'events');if(url)setForm(f=>({...f,poster_url:url}))}catch(x){setErr(true);setMsg(x.message)}finally{setBusy(false)}};
  return <div><h2 className="text-2xl font-bold">Events</h2><p className="mb-5 text-sm text-slate-500">Create events and posters without changing website code.</p><Notice message={msg} error={err}/>
    <form onSubmit={save} className="mb-8 rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 flex justify-between"><h3 className="font-bold">{editing?'Edit event':'New event'}</h3>{editing&&<button type="button" className={ghost} onClick={()=>{setEditing(null);setForm(blank)}}><X size={14}/>Cancel</button>}</div><div className="grid gap-4 md:grid-cols-2">
      <Field title="Title"><input className={input} required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field title="Date"><input type="date" className={input} required value={form.event_date} onChange={e=>setForm({...form,event_date:e.target.value})}/></Field>
      <Field title="Start time"><input type="time" className={input} value={form.start_time} onChange={e=>setForm({...form,start_time:e.target.value})}/></Field><Field title="End time"><input type="time" className={input} value={form.end_time} onChange={e=>setForm({...form,end_time:e.target.value})}/></Field>
      <Field title="Location"><input className={input} value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></Field><Field title="Speaker"><input className={input} value={form.speaker} onChange={e=>setForm({...form,speaker:e.target.value})}/></Field>
      <Field title="Category"><input className={input} value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></Field><Field title="Poster"><div className="flex gap-2"><input className={input} value={form.poster_url} placeholder="Image URL or upload →" onChange={e=>setForm({...form,poster_url:e.target.value})}/><label className={`${ghost} cursor-pointer`}><Upload size={15}/><input type="file" accept="image/*" className="hidden" onChange={poster}/></label></div></Field>
      <Field title="Registration URL"><input className={input} value={form.registration_url} onChange={e=>setForm({...form,registration_url:e.target.value})}/></Field><Field title="Livestream URL"><input className={input} value={form.livestream_url} onChange={e=>setForm({...form,livestream_url:e.target.value})}/></Field>
      <Field title="Description" className="md:col-span-2"><textarea rows="3" className={input} value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></Field>
    </div><div className="mt-4 flex flex-wrap gap-5 text-sm"><label><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/> Published</label><label><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured</label></div><button disabled={busy} className={`${primary} mt-4`}><Save size={15}/>{busy?'Saving…':'Save event'}</button></form>
    <div className="space-y-3">{rows.length===0?<Empty>No events yet.</Empty>:rows.map(r=><div key={r.id} className="flex flex-col gap-3 rounded-xl border bg-white p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="font-semibold">{r.title} {!r.published&&<span className="ml-2 rounded bg-amber-100 px-2 py-0.5 text-xs text-amber-700">Draft</span>}</div><div className="text-sm text-slate-500">{r.event_date} {r.start_time?.slice(0,5)} · {r.location}</div></div><div className="flex gap-2"><button className={ghost} onClick={()=>edit(r)}>Edit</button><button className={danger} onClick={()=>del(r.id)}><Trash2 size={14}/></button></div></div>)}</div>
  </div>;
}

function AnnouncementsSection(){const blank={title:'',body:'',kind:'info',published:true,starts_at:new Date().toISOString().slice(0,16),expires_at:''};const [rows,setRows]=useState([]),[form,setForm]=useState(blank),[msg,setMsg]=useState('');const load=useCallback(async()=>{const {data}=await supabase.from('announcements').select('*').order('created_at',{ascending:false});setRows(data||[])},[]);useEffect(()=>{load()},[load]);const save=async e=>{e.preventDefault();const payload={...form,starts_at:new Date(form.starts_at).toISOString(),expires_at:form.expires_at?new Date(form.expires_at).toISOString():null};const {error}=await supabase.from('announcements').insert(payload);setMsg(error?.message||'Announcement published.');if(!error){setForm(blank);load()}};const del=async id=>{if(confirm('Delete announcement?')){await supabase.from('announcements').delete().eq('id',id);load()}};return <div><h2 className="text-2xl font-bold">Announcements</h2><p className="mb-5 text-sm text-slate-500">Temporary notices can appear automatically on the public homepage.</p><Notice message={msg} error={msg&&!msg.includes('published')}/><form onSubmit={save} className="mb-6 rounded-2xl border bg-white p-5"><div className="grid gap-4 md:grid-cols-2"><Field title="Title"><input required className={input} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field title="Priority"><select className={input} value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option value="info">Info</option><option value="important">Important</option><option value="urgent">Urgent</option></select></Field><Field title="Starts"><input type="datetime-local" className={input} value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/></Field><Field title="Expires (optional)"><input type="datetime-local" className={input} value={form.expires_at} onChange={e=>setForm({...form,expires_at:e.target.value})}/></Field><Field title="Message" className="md:col-span-2"><textarea className={input} rows="3" value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></Field></div><button className={`${primary} mt-4`}><Plus size={15}/>Add announcement</button></form><div className="space-y-3">{rows.map(r=><div key={r.id} className="rounded-xl border bg-white p-4"><div className="flex items-start justify-between gap-4"><div><div className="font-semibold">{r.title}</div><p className="text-sm text-slate-600">{r.body}</p><p className="mt-1 text-xs text-slate-400">{r.kind} · {r.published?'Published':'Draft'} · {formatDateTime(r.starts_at)}</p></div><button className={danger} onClick={()=>del(r.id)}><Trash2 size={14}/></button></div></div>)}</div></div>}

function LivestreamSection(){const [form,setForm]=useState({enabled:false,provider:'youtube',title:'JIC Live',stream_url:'',scheduled_at:''}),[msg,setMsg]=useState('');useEffect(()=>{supabase.from('livestream_settings').select('*').eq('id',1).single().then(({data})=>data&&setForm({...data,scheduled_at:data.scheduled_at?new Date(data.scheduled_at).toISOString().slice(0,16):''}))},[]);const save=async()=>{let url=form.stream_url?.trim();if(url){try{const u=new URL(url);if(!['youtube.com','www.youtube.com','youtu.be','m.youtube.com','vimeo.com','www.vimeo.com','facebook.com','www.facebook.com'].includes(u.hostname))throw new Error('Use a trusted YouTube, Vimeo or Facebook URL.')}catch(x){setMsg(x.message||'Invalid URL');return}}const {error}=await supabase.from('livestream_settings').update({...form,stream_url:url||null,scheduled_at:form.scheduled_at?new Date(form.scheduled_at).toISOString():null}).eq('id',1);setMsg(error?.message||'Livestream settings saved.')};return <div><h2 className="text-2xl font-bold">Livestream</h2><p className="mb-5 text-sm text-slate-500">Enable this only when you want the public livestream section visible.</p><Notice message={msg} error={msg&&!msg.includes('saved')}/><div className="max-w-2xl rounded-2xl border bg-white p-5"><div className="grid gap-4"><Field title="Title"><input className={input} value={form.title||''} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field title="Provider"><select className={input} value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})}><option value="youtube">YouTube</option><option value="vimeo">Vimeo</option><option value="facebook">Facebook</option><option value="other">Other</option></select></Field><Field title="Stream URL"><input className={input} placeholder="https://www.youtube.com/watch?v=..." value={form.stream_url||''} onChange={e=>setForm({...form,stream_url:e.target.value})}/></Field><Field title="Scheduled time"><input type="datetime-local" className={input} value={form.scheduled_at||''} onChange={e=>setForm({...form,scheduled_at:e.target.value})}/></Field><label className="text-sm"><input type="checkbox" checked={!!form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/> Show livestream on the website</label></div><button onClick={save} className={`${primary} mt-4`}><Save size={15}/>Save livestream</button></div></div>}

function TeamSection(){const blank={name:'',role_title:'',bio:'',image_url:'',sort_order:0,published:true};const [rows,setRows]=useState([]),[form,setForm]=useState(blank),[msg,setMsg]=useState('');const load=useCallback(async()=>{const{data}=await supabase.from('team_members').select('*').order('sort_order');setRows(data||[])},[]);useEffect(()=>{load()},[load]);const save=async e=>{e.preventDefault();const {error}=await supabase.from('team_members').insert(form);setMsg(error?.message||'Team member added.');if(!error){setForm(blank);load()}};const photo=async e=>{try{const url=await uploadImage(e.target.files?.[0],'team');if(url)setForm({...form,image_url:url})}catch(x){setMsg(x.message)}};const del=async id=>{if(confirm('Delete team member?')){await supabase.from('team_members').delete().eq('id',id);load()}};return <div><h2 className="text-2xl font-bold">Meet the team</h2><p className="mb-5 text-sm text-slate-500">Manage public-facing team profiles.</p><Notice message={msg} error={msg&&!msg.includes('added')}/><form onSubmit={save} className="mb-6 rounded-2xl border bg-white p-5"><div className="grid gap-4 md:grid-cols-2"><Field title="Name"><input required className={input} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field title="Role/title"><input className={input} value={form.role_title} onChange={e=>setForm({...form,role_title:e.target.value})}/></Field><Field title="Photo"><div className="flex gap-2"><input className={input} value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/><label className={`${ghost} cursor-pointer`}><Upload size={14}/><input type="file" accept="image/*" className="hidden" onChange={photo}/></label></div></Field><Field title="Sort order"><input type="number" className={input} value={form.sort_order} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})}/></Field><Field title="Bio" className="md:col-span-2"><textarea className={input} rows="3" value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/></Field></div><button className={`${primary} mt-4`}><Plus size={15}/>Add person</button></form><div className="space-y-3">{rows.map(r=><div key={r.id} className="flex items-center gap-4 rounded-xl border bg-white p-4">{r.image_url&&<img src={r.image_url} className="h-12 w-12 rounded-full object-cover"/>}<div className="flex-1"><div className="font-semibold">{r.name}</div><div className="text-sm text-slate-500">{r.role_title}</div></div><button className={danger} onClick={()=>del(r.id)}><Trash2 size={14}/></button></div>)}</div></div>}

function UsersSection(){const {isSuperAdmin}=useAuth();const [rows,setRows]=useState([]),[email,setEmail]=useState(''),[name,setName]=useState(''),[role,setInviteRole]=useState('teacher'),[msg,setMsg]=useState('');const load=useCallback(async()=>{const{data,error}=await supabase.from('profiles').select('*').order('created_at');setRows(data||[]);if(error)setMsg(error.message)},[]);useEffect(()=>{load()},[load]);if(!isSuperAdmin)return <Empty>Only a Super Admin can manage user accounts and roles.</Empty>;const invoke=async body=>{const {data,error}=await supabase.functions.invoke('manage-user',{body});if(error)throw error;if(!data?.ok)throw new Error(data?.error||'Request failed');return data};const invite=async e=>{e.preventDefault();try{await invoke({action:'invite',email,display_name:name,role});setMsg('Invitation sent.');setEmail('');setName('');load()}catch(x){setMsg(x.message)}};const updateRole=async(id,newRole)=>{try{await invoke({action:'set_role',user_id:id,role:newRole});setMsg('Role updated.');load()}catch(x){setMsg(x.message)}};return <div><h2 className="text-2xl font-bold">Users & roles</h2><p className="mb-5 text-sm text-slate-500">Invitations are processed server-side; the Supabase service-role key never reaches the browser.</p><Notice message={msg} error={msg&&!/(sent|updated)/.test(msg)}/><form onSubmit={invite} className="mb-6 grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-4"><Field title="Name"><input className={input} value={name} onChange={e=>setName(e.target.value)}/></Field><Field title="Email"><input required type="email" className={input} value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field title="Role"><select className={input} value={role} onChange={e=>setInviteRole(e.target.value)}>{['teacher','events_manager','content_editor','admin','super_admin'].map(x=><option key={x}>{x}</option>)}</select></Field><div className="self-end"><button className={primary}><UserPlus size={15}/>Invite</button></div></form><div className="space-y-3">{rows.map(r=><div key={r.id} className="grid items-center gap-3 rounded-xl border bg-white p-4 md:grid-cols-[1fr_220px_100px]"><div><div className="font-semibold">{r.display_name||'User'}</div><div className="text-xs text-slate-400">{r.id}</div></div><select className={input} value={r.role} onChange={e=>updateRole(r.id,e.target.value)}>{['viewer','teacher','events_manager','content_editor','admin','super_admin'].map(x=><option key={x}>{x}</option>)}</select><span className={`text-sm ${r.is_active?'text-emerald-600':'text-red-600'}`}>{r.is_active?'Active':'Disabled'}</span></div>)}</div></div>}

function AuditSection(){const [rows,setRows]=useState([]);useEffect(()=>{supabase.from('audit_log').select('id,actor_id,table_name,record_id,action,created_at').order('created_at',{ascending:false}).limit(100).then(({data})=>setRows(data||[]))},[]);return <div><h2 className="text-2xl font-bold">Audit log</h2><p className="mb-5 text-sm text-slate-500">Latest 100 database changes.</p><div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Time</th><th className="p-3">Action</th><th className="p-3">Table</th><th className="p-3">Record</th><th className="p-3">Actor</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-3">{formatDateTime(r.created_at)}</td><td className="p-3 font-semibold">{r.action}</td><td className="p-3">{r.table_name}</td><td className="p-3 font-mono text-xs">{r.record_id}</td><td className="p-3 font-mono text-xs">{r.actor_id}</td></tr>)}</tbody></table></div></div>}

export default function AdminPage(){const {profile,role,signOut,can,isSuperAdmin}=useAuth();const allowed=useMemo(()=>SECTIONS.filter(([key,,,permission])=>key==='dashboard'||(key==='users'?isSuperAdmin:can(permission))),[can,isSuperAdmin]);const [active,setActive]=useState('dashboard');useEffect(()=>{if(!allowed.some(x=>x[0]===active))setActive('dashboard')},[allowed,active]);const section={dashboard:<DashboardSection onChoose={setActive}/>,prayer:<PrayerEditor/>,events:<EventsSection/>,announcements:<AnnouncementsSection/>,livestream:<LivestreamSection/>,content:<PageEditor/>,team:<TeamSection/>,users:<UsersSection/>,audit:<AuditSection/>}[active];return <div className="admin-console min-h-screen bg-slate-100 text-slate-900"><header className="sticky top-0 z-30 border-b bg-slate-950 text-white"><div className="flex min-h-16 items-center justify-between px-4 lg:px-6"><div><div className="font-bold">JIC Admin</div><div className="text-xs text-slate-400">{profile?.display_name||'User'} · {role}</div></div><div className="flex gap-2"><Link to="/" className={`${btn} bg-white/10 text-white hover:bg-white/20`}><Home size={15}/><span className="hidden sm:inline">Website</span></Link><button onClick={signOut} className={`${btn} bg-white/10 text-white hover:bg-red-500/20`}><LogOut size={15}/><span className="hidden sm:inline">Sign out</span></button></div></div></header><div className="mx-auto grid max-w-[1500px] lg:grid-cols-[240px_1fr]"><aside className="border-b bg-white p-3 lg:min-h-[calc(100vh-4rem)] lg:border-b-0 lg:border-r"><nav className="flex gap-2 overflow-x-auto lg:flex-col">{allowed.map(([key,name,Icon])=><button key={key} onClick={()=>setActive(key)} className={`flex shrink-0 items-center gap-2 rounded-lg px-3 py-2 text-left text-sm font-medium ${active===key?'bg-amber-100 text-amber-900':'text-slate-600 hover:bg-slate-50'}`}><Icon size={17}/>{name}</button>)}</nav></aside><main className="min-w-0 p-4 lg:p-8">{section}</main></div></div>}
